version: 0.2
# The cloud-auth lambda build needs env vars to generate a bundled config file
phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands: # NB this is a template so bash vars to use dollar-without-curly-braces style variables
      - cd "$CODEBUILD_SRC_DIR/src/aws-sam/cloud-auth"
      - ./build.sh
  post_build:
    commands:

artifacts:
  base-directory: src/aws-sam/cloud-auth
  discard-paths: yes
  files:
    - 'package.zip'
